server.port=9528
spring.application.name=financing
#spring.profiles.active=dev
# 使用旧版路径匹配策略
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# 解决日志中文乱码
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
logging.charset.console=UTF-8
logging.charset.file=UTF-8
####################################数据库配置####################################
spring.datasource.url=jdbc:mysql://rm-bp1loez79a8e3fd76eo.mysql.rds.aliyuncs.com:3306/financing?serverTimezone=GMT%2B8
spring.datasource.username=financing
spring.datasource.password=Sql140111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
####################################Thymeleaf配置(已禁用-前后端分离)####################################
# spring.thymeleaf.cache=false
# spring.thymeleaf.suffix=.html
# spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.servlet.content-type=text/html
# spring.thymeleaf.encoding=utf-8
# spring.messages.basename=i18n/messages
####################################redis配置####################################
spring.redis.database=0
spring.redis.host=r-bp1fp7r8b4agc6msczpd.redis.rds.aliyuncs.com
spring.redis.port=6379
spring.redis.username=financing
spring.redis.password=Redis140111
####################################CORS配置####################################
app.cors.allowed-origins=http://localhost:5173
